# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1143, 732)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        #####
        self.visualTools = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualTools.sizePolicy().hasHeightForWidth())
        self.visualTools.setSizePolicy(sizePolicy)
        self.visualTools.setObjectName("visualTools")
        self.AutToolCreation = QtWidgets.QWidget()
        self.AutToolCreation.setGeometry(QtCore.QRect(0, 0, 144, 479))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AutToolCreation.sizePolicy().hasHeightForWidth())
        self.AutToolCreation.setSizePolicy(sizePolicy)
        self.AutToolCreation.setObjectName("AutToolCreation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.AutToolCreation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addEvent = QtWidgets.QToolButton(self.AutToolCreation)
        self.addEvent.setStyleSheet("icons/alphabet.svg")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/alphabet.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEvent.setIcon(icon)
        self.addEvent.setIconSize(QtCore.QSize(24, 24))
        self.addEvent.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.addEvent.setAutoRaise(False)
        self.addEvent.setObjectName("addEvent")
        self.gridLayout_2.addWidget(self.addEvent, 1, 1, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.AutToolCreation)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/transition.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_2.addWidget(self.toolButton_5, 2, 2, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.AutToolCreation)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/pointer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon2)
        self.toolButton_8.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_2.addWidget(self.toolButton_8, 3, 1, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.AutToolCreation)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/final_state.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_2.addWidget(self.toolButton_4, 2, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.AutToolCreation)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/initial_state.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon4)
        self.toolButton_3.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_2.addWidget(self.toolButton_3, 2, 0, 1, 1)
        self.setupButton = QtWidgets.QToolButton(self.AutToolCreation)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setupButton.setIcon(icon5)
        self.setupButton.setIconSize(QtCore.QSize(24, 24))
        self.setupButton.setObjectName("setupButton")
        self.gridLayout_2.addWidget(self.setupButton, 1, 0, 1, 1)
        self.addState = QtWidgets.QToolButton(self.AutToolCreation)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/state.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addState.setIcon(icon6)
        self.addState.setIconSize(QtCore.QSize(24, 24))
        self.addState.setObjectName("addState")
        self.gridLayout_2.addWidget(self.addState, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.AutToolCreation)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/select.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon7)
        self.toolButton_7.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout_2.addWidget(self.toolButton_7, 3, 0, 1, 1)
        self.visualTools.addItem(self.AutToolCreation, "")
        self.gridLayout.addWidget(self.visualTools, 0, 0, 1, 1)
        self.Components = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Components.sizePolicy().hasHeightForWidth())
        self.Components.setSizePolicy(sizePolicy)
        self.Components.setObjectName("Components")
        self.statesAndEvents = QtWidgets.QWidget()
        self.statesAndEvents.setGeometry(QtCore.QRect(0, 0, 268, 405))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statesAndEvents.sizePolicy().hasHeightForWidth())
        self.statesAndEvents.setSizePolicy(sizePolicy)
        self.statesAndEvents.setObjectName("statesAndEvents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.statesAndEvents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.statesAndEvents)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.Components.addItem(self.statesAndEvents, "")
        self.automataList = QtWidgets.QWidget()
        self.automataList.setGeometry(QtCore.QRect(0, 0, 268, 447))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.automataList.sizePolicy().hasHeightForWidth())
        self.automataList.setSizePolicy(sizePolicy)
        self.automataList.setObjectName("automataList")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.automataList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.automataList)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.Components.addItem(self.automataList, "")
        self.gridLayout.addWidget(self.Components, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(416, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.autUnknown = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autUnknown.sizePolicy().hasHeightForWidth())
        self.autUnknown.setSizePolicy(sizePolicy)
        self.autUnknown.setObjectName("autUnknown")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.autUnknown)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget.addTab(self.autUnknown, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self, self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1143, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExportAs = QtWidgets.QAction(MainWindow)
        self.actionExportAs.setObjectName("actionExportAs")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionVisualTools = QtWidgets.QAction(MainWindow)
        self.actionVisualTools.setObjectName("actionVisualTools")
        self.actionStatesAndEvents = QtWidgets.QAction(MainWindow)
        self.actionStatesAndEvents.setObjectName("actionStatesAndEvents")
        self.actionAutomataList = QtWidgets.QAction(MainWindow)
        self.actionAutomataList.setObjectName("actionAutomataList")
        self.actionVerify = QtWidgets.QAction(MainWindow)
        self.actionVerify.setObjectName("actionVerify")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionCompile = QtWidgets.QAction(MainWindow)
        self.actionCompile.setObjectName("actionCompile")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAboutFireDES = QtWidgets.QAction(MainWindow)
        self.actionAboutFireDES.setObjectName("actionAboutFireDES")
        self.actionAboutLACSED = QtWidgets.QAction(MainWindow)
        self.actionAboutLACSED.setObjectName("actionAboutLACSED")
        self.actionSetup = QtWidgets.QAction(MainWindow)
        self.actionSetup.setObjectName("actionSetup")
        self.actionAddEvents = QtWidgets.QAction(MainWindow)
        self.actionAddEvents.setObjectName("actionAddEvents")
        self.actionAddState = QtWidgets.QAction(MainWindow)
        self.actionAddState.setObjectName("actionAddState")
        self.actionAddInitialState = QtWidgets.QAction(MainWindow)
        self.actionAddInitialState.setObjectName("actionAddInitialState")
        self.actionSetInitialState = QtWidgets.QAction(MainWindow)
        self.actionSetInitialState.setObjectName("actionSetInitialState")
        self.actionAddFinalState = QtWidgets.QAction(MainWindow)
        self.actionAddFinalState.setObjectName("actionAddFinalState")
        self.actionAddTransition = QtWidgets.QAction(MainWindow)
        self.actionAddTransition.setObjectName("actionAddTransition")
        self.actionSetInitialState_2 = QtWidgets.QAction(MainWindow)
        self.actionSetInitialState_2.setObjectName("actionSetInitialState_2")
        self.actionSetFinalState = QtWidgets.QAction(MainWindow)
        self.actionSetFinalState.setObjectName("actionSetFinalState")
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setObjectName("actionSelect")
        self.actionSelectNone = QtWidgets.QAction(MainWindow)
        self.actionSelectNone.setObjectName("actionSelectNone")
        self.actionProjectAutomata = QtWidgets.QAction(MainWindow)
        self.actionProjectAutomata.setObjectName("actionProjectAutomata")
        self.actionProjectSettings = QtWidgets.QAction(MainWindow)
        self.actionProjectSettings.setObjectName("actionProjectSettings")
        self.actionProject = QtWidgets.QAction(MainWindow)
        self.actionProject.setObjectName("actionProject")
        self.actionAutomaton = QtWidgets.QAction(MainWindow)
        self.actionAutomaton.setObjectName("actionAutomaton")
        self.menuNew.addAction(self.actionProject)
        self.menuNew.addAction(self.actionAutomaton)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionExportAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionProjectAutomata)
        self.menuEdit.addAction(self.actionProjectSettings)
        self.menuView.addAction(self.actionVisualTools)
        self.menuView.addAction(self.actionStatesAndEvents)
        self.menuView.addAction(self.actionAutomataList)
        self.menuTools.addAction(self.actionSetup)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionAddEvents)
        self.menuTools.addAction(self.actionAddState)
        self.menuTools.addAction(self.actionAddInitialState)
        self.menuTools.addAction(self.actionAddFinalState)
        self.menuTools.addAction(self.actionAddTransition)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSetInitialState_2)
        self.menuTools.addAction(self.actionSetFinalState)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSelect)
        self.menuTools.addAction(self.actionSelectNone)
        self.menuRun.addAction(self.actionVerify)
        self.menuRun.addAction(self.actionRun)
        self.menuRun.addAction(self.actionCompile)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAboutFireDES)
        self.menuHelp.addAction(self.actionAboutLACSED)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.visualTools.setCurrentIndex(0)
        self.Components.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FireDES"))
        self.addEvent.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/alphabet.svg\"/></p></body></html>"))
        self.addEvent.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/alphabet.svg\"/></p></body></html>"))
        self.addEvent.setText(_translate("MainWindow", "Add Event"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.toolButton_8.setText(_translate("MainWindow", "..."))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.setupButton.setText(_translate("MainWindow", "..."))
        self.addState.setText(_translate("MainWindow", "..."))
        self.toolButton_7.setText(_translate("MainWindow", "..."))
        self.visualTools.setItemText(self.visualTools.indexOf(self.AutToolCreation), _translate("MainWindow", "Visual Tools"))
        self.Components.setItemText(self.Components.indexOf(self.statesAndEvents), _translate("MainWindow", "States and Events"))
        self.Components.setItemText(self.Components.indexOf(self.automataList), _translate("MainWindow", "Automata List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.autUnknown), _translate("MainWindow", "unknown automaton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save as"))
        self.actionExportAs.setText(_translate("MainWindow", "Export as"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionVisualTools.setText(_translate("MainWindow", "Visual Tools"))
        self.actionStatesAndEvents.setText(_translate("MainWindow", "States and Events"))
        self.actionAutomataList.setText(_translate("MainWindow", "Automata list"))
        self.actionVerify.setText(_translate("MainWindow", "Verify"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionCompile.setText(_translate("MainWindow", "Compile"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionAboutFireDES.setText(_translate("MainWindow", "About FireDES"))
        self.actionAboutLACSED.setText(_translate("MainWindow", "About LACSED"))
        self.actionSetup.setText(_translate("MainWindow", "Project Setup"))
        self.actionAddEvents.setText(_translate("MainWindow", "Add Events"))
        self.actionAddState.setText(_translate("MainWindow", "Add State"))
        self.actionAddInitialState.setText(_translate("MainWindow", "Add Initial State"))
        self.actionSetInitialState.setText(_translate("MainWindow", "Set Initial State"))
        self.actionAddFinalState.setText(_translate("MainWindow", "Add Final State"))
        self.actionAddTransition.setText(_translate("MainWindow", "Add Transition"))
        self.actionSetInitialState_2.setText(_translate("MainWindow", "Set Initial State"))
        self.actionSetFinalState.setText(_translate("MainWindow", "Set Final State"))
        self.actionSelect.setText(_translate("MainWindow", "Select"))
        self.actionSelectNone.setText(_translate("MainWindow", "Select None"))
        self.actionProjectAutomata.setText(_translate("MainWindow", "Project automata"))
        self.actionProjectSettings.setText(_translate("MainWindow", "Project settings"))
        self.actionProject.setText(_translate("MainWindow", "Project"))
        self.actionAutomaton.setText(_translate("MainWindow", "Automaton"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
